# Generated by Django 4.2.9 on 2024-11-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city_profile_country_profile_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='zodiac_sign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
