# Generated by Django 4.2.9 on 2024-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_growth', models.CharField(max_length=500)),
                ('personal_growth_todo', models.CharField(blank=True, max_length=500, null=True)),
                ('success', models.CharField(max_length=500)),
                ('success_todo', models.CharField(blank=True, max_length=500, null=True)),
                ('relationships', models.CharField(max_length=500)),
                ('relationships_todo', models.CharField(blank=True, max_length=500, null=True)),
                ('affirmation', models.CharField(blank=True, max_length=500, null=True)),
                ('thinker', models.CharField(blank=True, max_length=500, null=True)),
                ('quote', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0)),
                ('max_tokens', models.IntegerField(default=200)),
                ('cache_duration', models.IntegerField(default=86400, help_text='In seconds')),
            ],
        ),
    ]
