# Generated by Django 4.2.9 on 2024-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_option_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
