# Generated by Django 4.2.9 on 2024-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_answer_selected_option_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_growth', models.CharField(max_length=500)),
                ('success', models.CharField(max_length=500)),
                ('relationships', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
