# Generated by Django 4.2.9 on 2024-11-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_promptsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsetting',
            name='max_tokens',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='promptsetting',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
