# Generated by Django 4.2.9 on 2024-12-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_alter_answer_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptsetting',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
