# Generated by Django 4.2.9 on 2024-12-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_full_name_profile_name_profile_zodiac_sign'),
        ('question', '0009_alter_promptsetting_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsetting',
            name='cache_duration',
            field=models.IntegerField(default=86400, help_text='In seconds'),
        ),
        migrations.CreateModel(
            name='HoroscopeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horoscope', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
