# Generated by Django 4.2.9 on 2024-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_promptsetting_cache_duration_horoscopelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsetting',
            name='affirmation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promptsetting',
            name='quote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promptsetting',
            name='thinker',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
