# Generated by Django 4.2.9 on 2024-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_promptsetting_affirmation_promptsetting_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsetting',
            name='personal_growth_todo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promptsetting',
            name='relationships_todo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promptsetting',
            name='success_todo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
