# Generated by Django 4.2.9 on 2024-12-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_full_name_profile_name_profile_zodiac_sign'),
        ('question', '0012_promptsetting_personal_growth_todo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(max_length=100, unique=True)),
                ('todos', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personal_growth_checked', models.BooleanField(default=False)),
                ('success_checked', models.BooleanField(default=False)),
                ('relationships_checked', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
